#!/usr/bin/env python3
"""Build the self-contained report from checked-in result tables."""
import csv
from html import escape
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parent
RAW=ROOT/'raw'

def read(name):
    with (RAW/name).open() as f: return list(csv.DictReader(f))

def table(headers,rows):
    return '<div class="table-wrap"><table><thead><tr>'+''.join('<th>'+escape(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(v)+'</td>' for v in r)+'</tr>' for r in rows)+'</tbody></table></div>'

def ratio(v): return f'{float(v):.3f}×'

def pct(v): return f'{(float(v)-1)*100:+.1f}%'

analysis=json.loads((RAW/'analysis.json').read_text())
profile=json.loads((RAW/'instrumentation-summary.json').read_text())
model=read('model-summary.csv')
fresh=read('stress-fresh_seeds.paired.csv')
primary=read('heldout-h1.paired.csv')
explore=read('heldout-h2-exploratory.paired.csv')
stress=read('stress-summary.csv')
labels={'ordinary':'Ordinary decode','default':'Current default','existing_cost_gate':'Existing optional cost gate','h1':'H1: all draft caps','h2':'H2: caps 0, 3, 5'}
for d in range(1,6): labels[f'fixed_{d}']=f'Fixed draft cap {d}'
modes=['resident_seed_batch','separate_seed']
by={(r['mode'],r['policy']):r for r in fresh}
baselines=table(['Policy','Seed batched: vs ordinary','Separate seed: vs ordinary'],[[labels[p],ratio(by[modes[0],p]['speedup_vs_ordinary']),ratio(by[modes[1],p]['speedup_vs_ordinary'])] for p in ['ordinary','default','existing_cost_gate',*[f'fixed_{d}' for d in range(1,6)],'h1','h2']])
validation=[]
for title,rows,p in [('H1 primary holdout',primary,'candidate'),('H2 reused holdout (exploratory)',explore,'candidate'),('H2 fresh seeds',fresh,'h2')]:
    for mode in modes:
        r=next(r for r in rows if r['mode']==mode and r['policy']==p)
        validation.append([title,'Batched seed' if mode==modes[0] else 'Separate seed',ratio(r['speedup_vs_default']),f"{float(r['vs_default_ci_low']):.3f}–{float(r['vs_default_ci_high']):.3f}",f"{r['runs_slower_than_default']}/240"])
validation_table=table(['Comparison','Execution model','Vs current default','95% interval','Runs slower than default'],validation)
model_table=table(['Raw continuation','Input tokens','Median TPS','Range (3 runs)','Std. dev.'],[[r['domain'].title(),r['context'],f"{float(r['median_tps']):.2f}",f"{float(r['min_tps']):.2f}–{float(r['max_tps']):.2f}",f"{float(r['stdev_tps']):.2f}"] for r in model])
stresslabels={'flat_draft':'Flat draft cost','expensive_verify':'Verification cost ×2','cheap_verify':'Verification cost ×0.5','short':'32 output tokens','long':'2048 output tokens','context_boundary':'Cross context bucket','noisy':'Higher cost noise','stable_easy':'Stable easy acceptance','stable_hard':'Stable hard acceptance','abrupt_recovery':'Hard → easy halfway','abrupt_collapse':'Easy → hard halfway'}
stress_table=[]
for kind,label in stresslabels.items():
    values=[]
    for mode in modes:
        rows={r['policy']:r for r in stress if r['stress']==kind and r['mode']==mode}
        values.append(ratio(float(rows['h2']['geometric_speedup_vs_ordinary'])/float(rows['default']['geometric_speedup_vs_ordinary'])))
    stress_table.append([label,*values])
stress_table=table(['Sensitivity case','H2 vs default: batched seed','H2 vs default: separate seed'],stress_table)
bycase=read('stress-fresh_seeds.by-case.csv')
case_table=[]
for domain in ['code','prose','structured']:
    for ctx in [256,2048]:
        rs=[next(r for r in bycase if r['case']==f'fresh_seeds-heldout-{domain}-{ctx}' and r['mode']==m and r['policy']=='h2') for m in modes]
        case_table.append([domain.title(),ctx,ratio(rs[0]['speedup_vs_default']),ratio(rs[1]['speedup_vs_default'])])
case_table=table(['Assumed regime','Initial context','H2 vs default: batched seed','H2 vs default: separate seed'],case_table)

# Neutral blue-gray surface, ink navy, teal data accent, amber caveat. Equal
# light/dark contrast. Body/system UI, tabular data, monospace formulas.
css='''
:root {color-scheme:light dark;--bg:#f2f6f8;--paper:#fff;--ink:#182b36;--muted:#526774;--accent:#006b86;--line:#d8e2e7;--warn:#935014;--soft:#eaf3f6;--warnsoft:#fff3e6;--chart:#16839b}
@media(prefers-color-scheme:dark){:root{--bg:#152028;--paper:#1c2b35;--ink:#e7f0f4;--muted:#a9bec9;--accent:#71cce2;--line:#3a4d58;--warn:#ffd0a2;--soft:#243d48;--warnsoft:#3d3026;--chart:#71cce2}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:17px/1.6 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:1120px;margin:auto;padding:44px 28px 72px;display:grid;gap:28px}header,section{background:var(--paper);border:1px solid var(--line);border-radius:8px;padding:26px;display:grid;gap:16px}h1,h2,h3,p{margin:0}h1{font-size:32px;line-height:1.2;letter-spacing:-.025em;text-wrap:balance}h2{font-size:23px;line-height:1.3}h3{font-size:18px}a{color:var(--accent);text-underline-offset:3px}a:focus-visible,summary:focus-visible{outline:3px solid var(--accent);outline-offset:4px}.meta,.note{color:var(--muted);font-size:14px}.tag{font-size:12px;font-weight:750;text-transform:uppercase;letter-spacing:.08em;color:var(--warn)}.decision{padding:14px 18px;border-left:4px solid var(--warn);background:var(--warnsoft)}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{background:var(--soft);padding:18px;border-radius:5px;display:grid;gap:6px}.value{font-size:30px;font-weight:730;color:var(--accent);font-variant-numeric:tabular-nums}.card span{font-size:14px;color:var(--muted)}.table-wrap{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:14px;font-variant-numeric:tabular-nums}th{text-align:left;color:var(--muted);font-weight:650;background:var(--soft)}td,th{padding:10px 12px;border-bottom:1px solid var(--line);vertical-align:top}tbody tr:last-child td{border-bottom:0}code,pre,.formula{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}code{font-size:.9em}.formula{background:var(--soft);padding:16px;font-size:15px;overflow-x:auto}ul,ol{margin:0;padding-left:23px}li+li{margin-top:8px}details{border-top:1px solid var(--line);padding-top:14px}summary{cursor:pointer;font-weight:650}details[open]>div{margin-top:16px;display:grid;gap:14px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:20px}.cols>div{display:grid;gap:10px}footer{color:var(--muted);font-size:13px}svg{width:100%;height:auto;color:var(--ink)}@media(max-width:760px){main{padding:20px 12px 40px}header,section{padding:19px}.cards,.cols{grid-template-columns:1fr}h1{font-size:27px}}
'''
html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cost-aware speculative scheduling: research result</title><style>{css}</style></head><body><main>
<header><div class="tag">Research result · no production change</div><h1>Cost-aware scheduling did not establish a reliable resident speedup</h1><p class="meta">21 September 2026 · DwarfStar <code>9139e2a</code> · M5 Max, 64 GiB · ordinary model measurements + synthetic scheduling experiments</p><p class="decision"><strong>Keep the current production behavior.</strong> No compatible speculative drafter was installed. The most promising small policy still failed to beat the current resident scheduler reliably in the synthetic validation. No model-level speculative gain is claimed.</p><div class="cards"><div class="card"><div class="value">0.994×</div><strong>H2 vs current default</strong><span>Fresh-seed resident simulation; interval 0.984–1.004</span></div><div class="card"><div class="value">1.032×</div><strong>Separate-seed simulation</strong><span>Small average gain, with workload regressions; assumed costs</span></div><div class="card"><div class="value">9–10 TPS</div><strong>Ordinary local generation</strong><span>Real SSD-streamed model, 3 runs per workload/context</span></div></div></header>
<section><h2>What was possible on this machine</h2><p>The installed model is DeepSeek V4 Flash 0731 IQ2XXS/w2Q2K, with 80.76 GiB of weights. It cannot stay fully resident in 64 GiB of memory. Its matching DSpark support file was absent, and no supported Qwen or GLM GGUF with built-in drafting was found. No checkpoints were downloaded.</p><p>DSpark is a small helper that proposes future tokens; the main model checks them before committing output. Without that helper, this campaign could measure ordinary decoding and isolated GPU operations, but could not test speculative model output, recovery or speed. The authorized fallback was used. The work is isolated on <a href="https://github.com/hermdawg/ds4/tree/codex/cost-aware-spec-20260921">your research branch</a>; production source files are unchanged.</p><p class="note">The local checkout was frozen rather than mixing the experiment with 62 newer upstream commits. Main checkout and existing user files were preserved. The campaign began at 20:44:55 UTC and stopped early after completing the fallback study. Further model-level optimization requires the missing matched drafter; more invented-cost trials cannot resolve that blocker.</p></section>
<section><h2>What the existing scheduler already does</h2><p>The current DSpark scheduler checks accepted-draft counts over short windows, pauses unproductive drafting, retries later, uses confidence to skip proposals, and avoids the output tail. It also has optional elapsed-cost gates, disabled by default to keep the schedule reproducible. Qwen has a different acceptance-based policy for one or two drafts.</p><p>Two details matter for cost accounting: resident M5 seed batching starts at three proposals, and a smaller verification cap can be applied after much of the draft work has happened. A seed is useful output, but it is not a successful draft. The existing optional cost gate is not a direct full-cycle cost-per-token comparison and may use an old ordinary-token cost.</p><p>The candidates learn a ratio of elapsed cycle time to committed tokens, including draft, verification and recovery. They also sample ordinary decode and occasionally retry other caps. H1 tries caps 0–5. H2 tries only 0, 3 and 5. Both were calibrated on the tuning split and frozen before evaluation.</p></section>
<section><h2>Held-out results: synthetic scheduling only</h2><p><strong>Every cost and acceptance probability in these comparisons is an assumption.</strong> The control decisions call the actual checked-in C scheduler. They do not turn the simulated execution into a model benchmark. Six workload/context cases, 256 output tokens, 40 seeds per case and execution mode. Ratios above 1 favor the candidate.</p>{validation_table}<p class="note">Paired geometric speedups; 95% bootstrap intervals resample seed clusters across the six fixed cases. They describe simulation noise, not generalization to real prompts. H2's original-holdout reuse is exploratory. Fresh seeds are a sensitivity check of the same assumed regimes.</p><p>H1 regressed on the primary resident comparison. H2's +0.5% exploratory resident result did not survive fresh seeds. In those fresh runs, H2 was slower than ordinary decoding in 77/240 resident cases and slower than the current default in 94/240. Its worst single resident run was 0.650× the default's simulated rate.</p><details><summary>All baselines on fresh-seed held-out regimes</summary><div>{baselines}<p class="note">Fixed depths use the supported DSpark verification-cap range with scheduling disabled. The learned/default schedules retain the ten-token tail guard. “Separate seed” describes execution accounting, not calibrated SSD performance.</p></div></details><details><summary>Workload-level regressions</summary><div>{case_table}<p>Structured regimes regress by about 11–13% against the resident default. Prose gains relative to the speculative default often still lose to ordinary decoding. An average benefit therefore does not justify a universal default.</p></div></details></section>
<section><h2>Where the policy fails</h2><p>The frozen stress matrix tested 12 conditions, including fresh seeds, with 40 seeds per case. H2 spends time on exploration when acceptance is already consistently good. Its discounted history responds slowly after acceptance collapses. Flat draft costs weaken the benefit of selecting shallower caps.</p>{stress_table}<p class="note">These are H2/default geometric ratios in assumed regimes. With expensive verification, H2 is still slower than ordinary decode: 0.964× resident and 0.978× separate-seed. Stable-hard cases also lose to ordinary. The policy was not retuned on these outcomes.</p></section>
<section><h2>Real ordinary-model baseline</h2><p>Unmodified Metal decoding with an 8 GiB SSD expert-cache budget, 4096 allocated context, 256-token prefill chunks and greedy output. Frozen raw coding, prose and JSON-like continuations were sliced at exact input frontiers. Each run generated 256 tokens. TPS means tokens/s/request; prefill time is reported separately in the raw CSV.</p>{model_table}<p>The runtime planned 16.27 GiB of memory. This was a disk-heavy experiment: system counters recorded 467–484 GiB of disk transfers per two-frontier run, including prefill and other system activity. System swap usage rose from 2 to 458 MiB across the suite, with no swap-ins in those per-job windows. Background load and paging limit interpretation of the timing variation. These results were not used to calibrate the synthetic resident costs.</p><p class="note">Current speculative scheduling and fixed-depth model baselines: unavailable without matching draft weights. No sampled model comparison was run. The existing exact-sampling unit tests passed without changing their tolerance.</p></section>
<section><h2>Instrumentation can change what it measures</h2><div class="cols"><div><h3>Host bookkeeping</h3><p>In the isolated C build, policy selection plus two monotonic timer reads took about 38 ns/cycle, comparable to two timer reads alone. This does not include GPU synchronization or inference integration.</p><h3>Real SSD timing counters</h3><p>Eight ordinary-model runs in ABBA/BAAB order produced identical greedy text. The existing timing summary changed paired elapsed time by a median <strong>{(profile['median_paired_time_ratio']-1)*100:.1f}%</strong>, with pair ratios {', '.join(f'{x:.3f}' for x in profile['paired_time_ratios'])}. The spread makes this a rough overhead estimate. Timed runs are diagnostic, not the headline baseline.</p></div><div><h3>GPU completion boundaries</h3><p>For three isolated Q8 projections, adding a wait after each stage changed median elapsed time from 0.192 to 0.491 ms at width 1024/one row, and from 0.461 to 0.772 ms at width 4096/six rows. All timing variants matched exactly and passed an independent dot-product reference.</p><p><strong>Measure complete cycles at existing synchronization points.</strong> Host enqueue timestamps measure submission, not completed GPU work. If stage detail needs extra waits, measure it separately and quantify its overhead.</p></div></div><p class="note">The projection benchmark is not a transformer, draft model or verifier. Existing SSD counters overlap in time and cannot be added to reconstruct full generation time. New speculative-stage instrumentation overhead remains unverified.</p></section>
<section><h2>Why the break-even point changes</h2><p>Let <em>t</em> be the cost of one ordinary target token, <em>D</em> draft cost, <em>V</em> verification cost, <em>R</em> expected recovery cost, and <em>A</em> expected accepted drafts. A cycle commits one seed plus <em>A</em> drafts. Its cost per token is total cycle cost divided by <em>1 + A</em>.</p><div class="formula">Separate seed: (t + D + P(verify)V + R)/(1 + A) &lt; t<br>⇒ D + P(verify)V + R &lt; tA<br><br>Batched seed, all proposals verified: (D + V + R)/(1 + A) &lt; t<br>⇒ D + V + R &lt; t(1 + A)</div><p>For example, if <em>t</em> = 20 ms and draft + verification + recovery = 32 ms, a separate-seed cycle that always verifies needs more than 1.6 accepted drafts. If the same 32 ms cycle already includes the seed, it needs more than 0.6. Those numbers illustrate the accounting; they are not measured model costs.</p><details><summary>Acceptance and estimator derivation</summary><div><p>If each proposed token independently matches with probability <em>p</em>, draft position <em>i</em> survives only if all <em>i</em> preceding decisions succeed, with probability <em>p</em><sup>i</sup>. Summing survival probabilities gives the expected accepted prefix:</p><div class="formula">A = p + p² + … + pᵈ = p(1 − pᵈ)/(1 − p), for p ≠ 1.<br>A = d when p = 1.</div><p>The simulator allows different first/later probabilities and confidence-pruned proposals. The C policy does not assume independent acceptance: it observes actual committed counts supplied by its caller. For an action, it updates time sum <em>S</em> and token sum <em>N</em> as follows:</p><div class="formula">S ← 0.95 S + elapsed_ms<br>N ← 0.95 N + committed_tokens<br>estimated cost per token = S/N</div><p>A ratio of totals weights each token correctly. Averaging per-cycle ratios would give a one-token rejection and a six-token acceptance the same weight. The 0.95 decay retains roughly 20 observations per action; rarely tried actions can therefore hold stale evidence for many output tokens. Exploration helps recovery but also has a cost.</p></div></details></section>
<section><h2>Correctness and the retained patch</h2><p>No production implementation was changed. The retained patch lives under <code>research/cost-aware-spec-20260921/</code>: a small backend-independent policy, source-backed control bridge, frozen inputs, bounded runners, tests, raw data and this report.</p><ul><li>Passed the existing sampling distribution checks, CPU/GPU session-state tests, speculative rollback test, Qwen kernels, MoE reference comparisons, SSD expert eviction, GLM recurrent kernels, Q8 projection tests, Metal kernel group and server unit group.</li><li>Passed policy sanitizer tests for invalid timings, weighted ratios, legal depths, output limits, context buckets, reset and recovery. Analytical simulator checks and replay of frozen H1 outcomes also passed.</li><li>Fixed a nested-timeout cleanup trap in the research runner; tests verify child processes stop. Final analysis refuses incomplete model results.</li><li>Still unverified: speculative model correctness, rejection/cache/recurrent-state integration, real exact-sampling behavior under the new policy, session reuse with policy-driven execution, and any CUDA performance claim. Unit tests cannot replace these checks.</li></ul></section>
<section><h2>What should transfer to NVIDIA serving</h2><p>The useful idea is the accounting: include all elapsed work, compare against ordinary decoding, count committed tokens, respect output limits, and retain occasional exploration. Re-measure draft/verification/recovery costs, context effects and legal caps on the intended hardware. CUDA graph size boundaries and expert activation can make cost curves uneven.</p><p>Concurrent requests change the objective. A draft that speeds up one request may consume verification capacity needed by others. Optimize useful aggregate throughput in tok/s/GPU while checking TPS and latency. This local single-request campaign establishes no production-serving gain.</p><p>There is relevant prior art: <a href="https://vllm.ai/blog/2026-08-14-dspark-adaptive-verification">vLLM's DSpark adaptive verification</a> already uses separate profiled cost tables and confidence survival to choose a global verification budget. <a href="https://arxiv.org/abs/2605.00342v2">EVICT</a> studies verification costs from activating more experts. These sources motivate a batch-aware follow-up; their performance figures are not part of this report.</p><p><strong>Most promising next experiment:</strong> use a resident matched target/drafter pair, first measure ordinary and fixed caps 3 and 5, then test cost plus existing confidence signals in interleaved runs. Include concurrent-request batches before considering a serving change. No new drafter training or broad CUDA port is justified by these results.</p></section>
<section><h2>Reproduce and inspect</h2><p><a href="README.md">Build and benchmark commands</a> · <a href="LEDGER.md">Experiment ledger</a> · <a href="EXPERIMENTS.md">Frozen hypotheses and protocol</a> · <a href="SOURCES.md">Code and prior-art references</a></p><p><a href="raw/model-summary.csv">Ordinary model summary</a> · <a href="raw/model-all.csv">All model runs</a> · <a href="raw/heldout-h1.csv">Primary H1 raw results</a> · <a href="raw/stress-fresh_seeds.csv">Fresh-seed raw comparison</a> · <a href="raw/stress-summary.csv">Sensitivity summary</a> · <a href="raw/kernel-cost.csv">GPU timing observations</a> · <a href="raw/streaming-profile-all.csv">Instrumentation pairs</a></p></section>
<footer>All measurements and negative results are retained on the isolated research branch. Source baseline: 9139e2a. No model downloads, training, CUDA deployment, acceptance-rule changes or recurring jobs.</footer>
</main></body></html>'''
(ROOT/'report.html').write_text(html)
print(ROOT/'report.html')
